export const missionTitlesData : string[] = [
    `Broken swords`,
    `The Smoke Forest`,
    `The Fallen Island`,
    `Town of Onyx`,
    `Lands of the Damned`,
    `The Windy Town`,
    `Vault of Coal`,
    `The Inferno Town`,
    `Cove of Nightmares`,
    `The Dark Outpost`,
    `Farms of Necrosis`,
    `Borough of Fire`,
    `The Shadow Shore`,
    `City of Dread`,
    `The Molded River`,
    `Shore of Ghosts`,
    `Cove of Ash`,
    `The Crumbled Labyrinth`,
    `The Bleak Isle`,
    `Reef of Hauntings`,
    `Cove of Whispers`,
    `The Smoke Borough`,
    `Temple of Remnants`,
    `The Doom Lands`,
    `Forest of Ruins`,
    `The Agony Vault`,
    `The Chaos City`,
    `Reef of the Unknown`,
    `The Necrotic Borough`,
    `The Crumbling Fields`,
    `Town of Phantoms`,
    `Island of Undoing`,
    `Borough of Waste`,
    `Village of Ghosts`,
    `The End Cove`,
    `Cove of Death`,
    `Farms of the Fallen`,
    `Cove of Death`,
    `Harbor of Illusions`,
    `Borough of the Abandoned`,
    `The Destruction Temple`,
    `The Molten Reef`,
    `Lands of the Forgotten`
]