export const papyrusSrcData : string[] = [
  './missions/papyrus/papyrus_1.png',
  './missions/papyrus/papyrus_2.png',
  './missions/papyrus/papyrus_3.png',
  './missions/papyrus/papyrus_4.png',
  './missions/papyrus/papyrus_5.png',
  './missions/papyrus/papyrus_6.png',
  './missions/papyrus/papyrus_7.png',
  './missions/papyrus/papyrus_8.png',
  './missions/papyrus/papyrus_9.png',
  './missions/papyrus/papyrus_10.png',
  './missions/papyrus/papyrus_11.png',
  './missions/papyrus/papyrus_12.png',
  './missions/papyrus/papyrus_13.png',
  './missions/papyrus/papyrus_14.png',
]